import json

with open('food_vectors.js', 'r') as f:
    text = f.read()

import re
import ast

def parse_vectors(text, var_name):
    # Find window.FOOD_VECTORS = {...};
    pattern = r'window\.' + var_name + r'\s*=\s*(\{.*?\});'
    match = re.search(pattern, text, re.DOTALL)
    if not match: return {}
    obj_str = match.group(1)
    
    # Replace some javascript-isms if any, but since it's generated by json.dumps, it's mostly valid JSON
    # Wait, the python script generated it as `window.FOOD_VECTORS = { ... };`
    return json.loads(obj_str)

food_vectors = parse_vectors(text, "FOOD_VECTORS")

uni_vec = food_vectors.get("ウニ")
if not uni_vec:
    print("ウニ not found in FOOD_VECTORS!")
    exit(1)

def dot_product(v1, v2):
    return sum(a*b for a, b in zip(v1, v2))

print("Similarity with UNI >= 0.55:")
for word, vec in food_vectors.items():
    sim = dot_product(uni_vec, vec)
    if sim >= 0.55:
        print(f"{word}: {sim:.4f}")

